services:
  - type: web
    name: flask-blog
    env: python
    buildCommand: "pip install -r requirements.txt"
  # 修正 gunicorn 匯入問題
    startCommand: "gunicorn myblog.app:app"
    workingDirectory: .
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        value: "d109a20770c9b0e2acdf0f81e81ee96c440f69b4cea2bfd3"
